// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyB79nEd9hJisPrfKiujPHrCQOZZt-zQ',
    appId: '1:669236338298:web:7d96a5ab681fd03be825c3',
    messagingSenderId: '669236338298',
    projectId: 'theeasyfitclinics-dbd1b',
    authDomain: 'theeasyfitclinics-dbd1b.firebaseapp.com',
    storageBucket: 'theeasyfitclinics-dbd1b.firebasestorage.app',
    measurementId: 'G-NGP3VDW16L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA80aFveQBPkH2s7hI9ngUw76tmMnojXqA',
    appId: '1:669236338298:android:32d8279afe280288e825c3',
    messagingSenderId: '669236338298',
    projectId: 'theeasyfitclinics-dbd1b',
    storageBucket: 'theeasyfitclinics-dbd1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApX_zfVJI6LAQwXCF2bk4eE4cQ6ArR844',
    appId: '1:669236338298:ios:5acad1656ca1435ee825c3',
    messagingSenderId: '669236338298',
    projectId: 'theeasyfitclinics-dbd1b',
    storageBucket: 'theeasyfitclinics-dbd1b.firebasestorage.app',
    iosBundleId: 'com.example.theEasyfitClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApX_zfVJI6LAQwXCF2bk4eE4cQ6ArR844',
    appId: '1:669236338298:ios:5acad1656ca1435ee825c3',
    messagingSenderId: '669236338298',
    projectId: 'theeasyfitclinics-dbd1b',
    storageBucket: 'theeasyfitclinics-dbd1b.firebasestorage.app',
    iosBundleId: 'com.example.theEasyfitClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUyB79nEd9hJisPrfKiujPHrCQOZZt-zQ',
    appId: '1:669236338298:web:74608c7980c4cbd9e825c3',
    messagingSenderId: '669236338298',
    projectId: 'theeasyfitclinics-dbd1b',
    authDomain: 'theeasyfitclinics-dbd1b.firebaseapp.com',
    storageBucket: 'theeasyfitclinics-dbd1b.firebasestorage.app',
    measurementId: 'G-PWW52DJWVK',
  );
}
